[workspace]
name = "wasp_autonomous_systems_gazebo"
authors = ["Patric Jensfelt <patric@kth.se>"]
channels = [
	"https://prefix.dev/pixi-build-backends",
	"https://prefix.dev/conda-forge",
	"https://prefix.dev/robostack-jazzy",
]
version = "0.1.0"
platforms = [
	"osx-arm64",
	"linux-64",
]
preview = ["pixi-build"]

# See ../docs/notes-gazebo-design.md

[activation.env]
GZ_IP = "127.0.0.1"

[dependencies]
ros-jazzy-desktop = "*"

ros-jazzy-compressed-image-transport = "*"

ros-jazzy-ros-gz-sim = "*"
ros-jazzy-ros-gz-bridge = "*"
ros-jazzy-actuator-msgs = "*"
ros-jazzy-control-msgs = "*"
ros-jazzy-turtlebot3-gazebo = "*"

ros-jazzy-teleop-twist-keyboard = "*"
ros-jazzy-tf-transformations = "*"

setuptools = "==69.2.0"
colcon-ros = "*"
zstd = ">=1.5.7,<2"

ros-jazzy-wasp-as-interfaces = { path = "../src/wasp_as_interfaces/package.xml" }
ros-jazzy-wasp-autonomous-systems-interfaces = { path = "../src/wasp_autonomous_systems_interfaces/package.xml" }

ultralytics = "*"
torchvision = "*"
transformers = "*"
matplotlib = "*"
transforms3d = "*"
numpy = "*"
opencv = "*"
pyqtgraph = "*"
kdtree = "*"

[target.unix.activation]
scripts = ["install/setup.sh"]

[tasks]

build = { cmd = "bash -c 'export LIBRARY_PATH=\"$CONDA_PREFIX/lib:$LIBRARY_PATH\" && colcon build --symlink-install --paths ../src/wasp_as ../src/wasp_as_ass_1 ../src/wasp_as_ass_2 ../src/wasp_as_ass_3 ../src/wasp_as_ass_4 ../src/wasp_as_interfaces ../src/wasp_autonomous_systems_interfaces src/wasp_as_gazebo --cmake-args -DPython_EXECUTABLE=$CONDA_PREFIX/bin/python -DPython3_EXECUTABLE=$CONDA_PREFIX/bin/python -DPYTHON_EXECUTABLE=$CONDA_PREFIX/bin/python -DPython3_FIND_STRATEGY=LOCATION -DPython_FIND_STRATEGY=LOCATION'", depends-on = [
	"postinstall_notice",
] }

download_rosbags = { cmd = 'curl -fSL "https://canvas.kth.se/files/9471655/download?download_frd=1&verifier=4wOMCwu3QHS0duQGTKpn6HyhO9jCPGZSL3RM9kmu" | tar -C .. --use-compress-program=unzstd -x', depends-on = [
	"postinstall_notice",
] }

postinstall_notice = { cmd = "bash ../packaging/postinstall_notice.sh" }

ass_1_1 = { cmd = "ros2 launch wasp_as_gazebo ass_1_1_launch.py gui:={{ gui }}", args = [{ arg = "gui", default = "auto" }] }
ass_1_1_teleop = { cmd = "ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -p stamped:=true -p key_timeout:=0.0 -p repeat_rate:=0.0 -p use_sim_time:=true" }
ass_1_2 = { cmd = "ros2 launch wasp_as_ass_1 real_robot_launch.xml rate:={{ rate }}", args = [{ arg = "rate", default = "1.0" }] }
ass_1_2_bag = { cmd = "ros2 bag play --read-ahead-queue-size 100 -l -r {{ rate }} --clock 100 ../rosbags/real_robot", args = [{ arg = "rate", default = "1.0" }] }
ass_1_3 = { cmd = "ros2 launch wasp_as_ass_1 kitti_launch.xml rate:={{ rate }}", args = [{ arg = "rate", default = "1.0" }] }
ass_1_3_bag = { cmd = "ros2 bag play --read-ahead-queue-size 100 -l -r {{ rate }} --clock 100 ../rosbags/kitti", args = [{ arg = "rate", default = "1.0" }] }

ass_2_collision = { cmd = "ros2 launch wasp_as_gazebo ass_2_collision_launch.py gui:={{ gui }}", args = [{ arg = "gui", default = "auto" }] }
ass_2_yolo = { cmd = "ros2 launch wasp_as_ass_2 kitti_segmentation_launch.xml rate:={{ rate }}", args = [{ arg = "rate", default = "1.0" }] }
ass_2_kitti_rosbag = { cmd = "ros2 bag play --read-ahead-queue-size 100 -l -r {{ rate }} --clock 100 -d 2.0 ../rosbags/kitti", args = [{ arg = "rate", default = "1.0" }] }
ass_2_gallery_sample = { cmd = "ros2 run wasp_as_ass_2 sample_kitti_gallery --ros-args -r /image:=/kitti/camera/color/left/image" }
ass_2_clip_retrieval = { cmd = "ros2 run wasp_as_ass_2 clip_retrieval {{ gallery }}", args = [{ arg = "gallery", default = "kitti" }] }
ass_2_dino_attention = { cmd = "ros2 run wasp_as_ass_2 dino_attention {{ gallery }}", args = [{ arg = "gallery", default = "kitti" }] }
ass_2_dino_correspondence = { cmd = "ros2 run wasp_as_ass_2 dino_correspondence {{ gallery }}", args = [{ arg = "gallery", default = "kitti" }] }
ass_2_grounding_dino = { cmd = "ros2 run wasp_as_ass_2 grounding_dino_detection {{ gallery }}", args = [{ arg = "gallery", default = "kitti" }] }

ass_3 = { cmd = "ros2 launch wasp_as_ass_3 planning_launch.xml" }
ass_3_planner = { cmd = "ros2 run wasp_as_ass_3 path_planner" }
ass_3_gui = { cmd = "ros2 launch wasp_as_ass_3 gui_launch.xml" }

ass_4_manual = { cmd = "ros2 launch wasp_as_gazebo ass_4_manual_launch.py gui:={{ gui }}", args = [{ arg = "gui", default = "auto" }] }
ass_4_pid = { cmd = "ros2 launch wasp_as_gazebo ass_4_pid_launch.py log_file:={{ log_file }} gui:={{ gui }}", args = [
	{ arg = "log_file", default = "none" },
	{ arg = "gui", default = "auto" },
] }

ass_2_odometry = { cmd = "ros2 launch wasp_as_ass_2 odometry_launch.xml rate:={{ rate }}", args = [{ arg = "rate", default = "1.0" }] }
ass_2_odometry_bag = { cmd = "ros2 bag play ../rosbags/real_robot --read-ahead-queue-size 100 -l -r {{ rate }} --clock 100 -d 2.0 --remap /motor/encoders:=/motor/encoders_legacy /motor/duty_cyles:=/motor/duty_cyles_legacy", args = [{ arg = "rate", default = "1.0" }] }
ass_elective_a = { cmd = "ros2 launch wasp_as_ass_2 kitti_segmentation_extra_launch.xml rate:={{ rate }} yolo_model:={{ yolo_model }}", args = [
	{ arg = "rate", default = "1.0" },
	{ arg = "yolo_model", default = "torch" },
] }
