[workspace]
authors = ["danielduberg <danielduberg@gmail.com>"]
channels = ["conda-forge"]
name = "wasp_autonomous_systems"
version = "0.1.0"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]

# This will automatically activate the ros workspace on activation
[target.win.activation]
scripts = ["install/setup.bat"]

[target.unix.activation]
# For activation scripts, we use bash for Unix-like systems
scripts = ["install/setup.bash"]

[dependencies]
python = "*"
# Build tools
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
# ROS specific tools
rosdep = "*"
colcon-common-extensions = "*"
setuptools = "==70.3.0"
# Assignment 3
kdtree = ">=0.16,<0.17"
transforms3d = ">=0.4.2,<0.5"
ultralytics = ">=8.3.234,<9"
pytorch-cpu = "==2.7"
torchvision = "==0.22"
openvino = ">=2025.0.0,<2026"
nncf = ">=2.5.0,<3"
opencv = ">=4.11.0,<5"

# [pypi-dependencies]
# pv = {  }

[target.linux.dependencies]
libgl-devel = "*"

# TODO: Make sure to source after build

# To build you can use - `pixi run -e <ros distro> build <Any other temporary args>`
[target.win-64.tasks]
build = { cmd = "colcon build --merge-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY", inputs = [
	"src",
	"setup.py",
	"setup.cfg",
] }

[target.unix.tasks]
build = { cmd = "colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY", inputs = [
	"src",
	"setup.py",
	"setup.cfg",
] }


[tasks]
download_rosbags = { cmd = 'curl -fSL "https://canvas.kth.se/files/9471655/download?download_frd=1&verifier=4wOMCwu3QHS0duQGTKpn6HyhO9jCPGZSL3RM9kmu" | tar -I "unzstd -T0" -x', outputs = [
	"rosbags/kitti/kitti_0.mcap",
	"rosbags/kitti/kitti_1.mcap",
	"rosbags/kitti/kitti_2.mcap",
	"rosbags/kitti/kitti_3.mcap",
	"rosbags/kitti/kitti_4.mcap",
	"rosbags/kitti/metadata.yaml",
	"rosbags/real_robot/real_robot_0.mcap",
	"rosbags/real_robot/real_robot_1.mcap",
	"rosbags/real_robot/real_robot_2.mcap",
	"rosbags/real_robot/real_robot_3.mcap",
	"rosbags/real_robot/metadata.yaml",
] }

generate_yolo_models = { cmd = '''
mkdir -p yolo_models
&& cd yolo_models
&& yolo segment export model=yolo11n-seg.pt format=openvino half=True device=cpu dynamic=True 
&& yolo segment export model=yolo11n-seg.pt format=openvino int8=True device=cpu dynamic=True data=coco128-seg.yaml
''', outputs = [
	"yolo_models/yolo11n-seg_int8_openvino_model/metadata.yaml",
	"yolo_models/yolo11n-seg_int8_openvino_model/yolo11n-seg.bin",
	"yolo_models/yolo11n-seg_int8_openvino_model/yolo11n-seg.xml",
	"yolo_models/yolo11n-seg_openvino_model/metadata.yaml",
	"yolo_models/yolo11n-seg_openvino_model/yolo11n-seg.bin",
	"yolo_models/yolo11n-seg_openvino_model/yolo11n-seg.xml",
	"yolo11n-seg.pt",
] }

# ros2 launch assignment_1 turtlebot_simulation_launch.py
# & rviz2 -d src/assignment_1/rviz/turtlebot_simulation.rviz --ros-args -p use_sim_time:=true
# & ros2 run turtlebot3_teleop teleop_keyboard
ass_1_task_1 = { cmd = '''
ros2 launch assignment_1 turtlebot_simulation_launch.py
& rviz2 -d src/assignment_1/rviz/turtlebot_simulation.rviz --ros-args -p use_sim_time:=true
''', depends-on = [
	"build",
] }
# ass_1_teleop = { cmd = "ros2 run turtlebot3_teleop teleop_keyboard" }

ass_1_task_2 = { cmd = '''
ros2 bag play --read-ahead-queue-size 100 -l -r 1.0 --clock 100 rosbags/kitti
& rviz2 -d src/assignment_1/rviz/kitti.rviz --ros-args -p use_sim_time:=true
& ros2 run image_transport republish --ros-args -p in_transport:="compressed" -p out_transport:="raw" --remap in/compressed:=/kitti/camera/color/left/image/compressed --remap out:=/kitti/camera/color/left/image
& ros2 run image_transport republish --ros-args -p in_transport:="compressed" -p out_transport:="raw" --remap in/compressed:=/kitti/camera/color/right/image/compressed --remap out:=/kitti/camera/color/right/image
& ros2 launch wasp_autonomous_systems kitti_car_launch.py
''', depends-on = [
	"download_rosbags",
] }
# ass_1_task_2 = { cmd = "ros2 bag play --read-ahead-queue-size 100 -l -r 1.0 --clock 100 rosbags/kitti", depends-on = [
# 	"download_rosbags",
# ] }
# ass_1_task_2_viz = { cmd = '''
# rviz2 -d src/assignment_1/rviz/kitti.rviz --ros-args -p use_sim_time:=true
# & ros2 run image_transport republish --ros-args -p in_transport:="compressed" -p out_transport:="raw" --remap in/compressed:=/kitti/camera/color/left/image/compressed --remap out:=/kitti/camera/color/left/image
# & ros2 run image_transport republish --ros-args -p in_transport:="compressed" -p out_transport:="raw" --remap in/compressed:=/kitti/camera/color/right/image/compressed --remap out:=/kitti/camera/color/right/image
# ''' }

ass_2_task_1 = { cmd = '''
ros2 run assignment_2 odometry --ros-args -p use_sim_time:=true
& ros2 bag play --read-ahead-queue-size 100 -l -r 1.0 --clock 100 -p rosbags/real_robot
& rviz2 -d src/assignment_2/rviz/odometry.rviz --ros-args -p use_sim_time:=true
& ros2 run image_transport republish --ros-args -p in_transport:="compressed" -p out_transport:="raw" --remap in/compressed:=/camera/color/image/compressed --remap out:=/camera/color/image
''', depends-on = [
	"build",
	"download_rosbags",
] }

ass_2_task_2 = { cmd = '''
ros2 launch assignment_2 collision_detection_launch.py
& rviz2 -d src/assignment_2/rviz/collision_detection.rviz --ros-args -p use_sim_time:=true
& pixi run ros2 run rqt_plot rqt_plot /imu/linear_acceleration
& ros2 run assignment_2 collision_detection --ros-args -p use_sim_time:=true
& ros2 run wasp_autonomous_systems autonomous_controller --ros-args -p use_sim_time:=true
''', depends-on = [ 
	"build",
] }

ass_2_task_3_kitti = { cmd = '''
ros2 run assignment_2 segmentation --ros-args -r /image:=/kitti/camera/color/left/image -p use_sim_time:=true -p yolo_model:="s"
& ros2 bag play --read-ahead-queue-size 100 -l -r 1.0 --clock 100 -p rosbags/kitti
& rviz2 -d src/assignment_2/rviz/kitti_segmentation.rviz --ros-args -p use_sim_time:=true
& ros2 run image_transport republish --ros-args -p in_transport:="compressed" -p out_transport:="raw" --remap in/compressed:=/kitti/camera/color/left/image/compressed --remap out:=/kitti/camera/color/left/image
& ros2 run image_transport republish --ros-args -p in_transport:="compressed" -p out_transport:="raw" --remap in/compressed:=/kitti/camera/color/right/image/compressed --remap out:=/kitti/camera/color/right/image
& ros2 launch wasp_autonomous_systems kitti_car_launch.py
''', depends-on = [
	"build",
	"download_rosbags",
	"generate_yolo_models",
] }

ass_2_task_3_cam = { cmd = '''
ros2 run assignment_2 camera --ros-args -p framerate:=10.0 -p image_height:=480 -p image_width:=640
& ros2 run rqt_image_view rqt_image_view /image
& ros2 run assignment_2 segmentation --ros-args -p yolo_model:="s"
& ros2 run rqt_image_view rqt_image_view /image_segmentation
''', depends-on = [
	"build",
	"generate_yolo_models",
] }

ass_3 = { cmd = '''
ros2 run assignment_3 path_planner
& rviz2 -d $PIXI_PROJECT_ROOT/src/assignment_3/rviz/planning.rviz
& ros2 run rqt_reconfigure rqt_reconfigure /path_planner
''', depends-on = ["build"] }
# ass_3_viz = { cmd = "rviz2 -d $PIXI_PROJECT_ROOT/src/assignment_3/rviz/planning.rviz", depends-on = [
# 	"build",
# ] }
# ass_3_rqt = { cmd = "ros2 run rqt_reconfigure rqt_reconfigure" }

[feature.jazzy]
channels = ["robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-desktop-full = ">=0.11.0,<0.12"
ros-jazzy-turtlebot3-simulations = ">=2.3.7,<3"
ros-jazzy-turtlebot3-teleop = ">=2.3.3,<3"
ros-jazzy-image-transport-plugins = ">=4.0.5,<5"
ros-jazzy-compressed-image-transport = ">=4.0.5,<5"
ros-jazzy-ros-gz = ">=1.0.16,<2"
ros-jazzy-tf-transformations = ">=1.1.0,<2"

[feature.jazzy.activation.env]
TURTLEBOT3_MODEL = "burger_cam"
GZ_SIM_RESOURCE_PATH = "$PIXI_PROJECT_ROOT/src/wasp_autonomous_systems/models:$GZ_SIM_RESOURCE_PATH"
YOLO_MODELS_DIR = "$PIXI_PROJECT_ROOT/yolo_models"

[target.osx.activation.env]
# Required for the RVIZ2 to properly startup on osx
# RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"

[environments]
default = { features = ["jazzy"] }
jazzy = { features = ["jazzy"] }
