[workspace]
name = "wasp_autonomous_systems"
authors = ["Daniel Duberg <danielduberg@gmail.com>"]
channels = [
	"https://prefix.dev/pixi-build-backends",
	"https://prefix.dev/conda-forge",
	"https://prefix.dev/robostack-humble",
]
version = "0.1.0"
platforms = [
	"osx-arm64",
	"linux-64",
	# "win-64", # TODO: Requires Jazzy for Gazebo support, change to Jazzy when https://github.com/RoboStack/ros-jazzy/pull/135 is merged
	# "linux-aarch64",
]
preview = ["pixi-build"]

[dependencies]
# ROS
# ros-jazzy-ros2run = ">=0.32.6,<0.33"
ros-humble-desktop = "*"
colcon-ros = "*"
# Course packages
ros-humble-wasp-as-ass-1 = { path = "src/wasp_as_ass_1" }
ros-humble-wasp-as-ass-2 = { path = "src/wasp_as_ass_2" }
ros-humble-wasp-as-ass-3 = { path = "src/wasp_as_ass_3" }
ros-humble-wasp-as-ass-4 = { path = "src/wasp_as_ass_4" }
ros-humble-wasp-as = { path = "src/wasp_as" }
ros-humble-wasp-as-interfaces = { path = "src/wasp_as_interfaces" }
# To decompress rosbags
zstd = ">=1.5.7,<2"

# This will automatically activate the ros workspace on activation
[target.win.activation]
scripts = ["install/setup.bat"]

[target.unix.activation]
scripts = ["install/setup.sh"]

# To build you can use - `pixi run -e <ros distro> build <Any other temporary args>`
[feature.build.target.win-64.tasks]
build = "colcon build --merge-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

[feature.build.target.unix.tasks]
build = "colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

[tasks]
download_rosbags = { cmd = 'curl -fSL "https://canvas.kth.se/files/9471655/download?download_frd=1&verifier=4wOMCwu3QHS0duQGTKpn6HyhO9jCPGZSL3RM9kmu" | tar --use-compress-program=unzstd -x', outputs = [
	"rosbags/kitti/kitti_*.mcap",
	"rosbags/kitti/metadata.yaml",
	"rosbags/real_robot/real_robot_*.mcap",
	"rosbags/real_robot/metadata.yaml",
] }

# Dev tasks

build = "colcon build --symlink-install --cmake-args -DPython_EXECUTABLE=$CONDA_PREFIX/bin/python -DPython3_EXECUTABLE=$CONDA_PREFIX/bin/python -DPYTHON_EXECUTABLE=$CONDA_PREFIX/bin/python -DPython3_FIND_STRATEGY=LOCATION -DPython_FIND_STRATEGY=LOCATION"

# Assignment 1 tasks

ass_1_1 = { cmd = "ros2 launch wasp_as_ass_1 turtlebot_simulation_launch.xml" }
ass_1_2 = { cmd = "ros2 launch wasp_as_ass_1 real_robot_launch.xml rate:={{ rate }}", args = [{ arg = "rate", default = "1.0" }] }
ass_1_3 = { cmd = "ros2 launch wasp_as_ass_1 kitti_launch.xml rate:={{ rate }}", args = [{ arg = "rate", default = "1.0" }] }

# Assignment 2 tasks

ass_2_1 = { cmd = "ros2 launch wasp_as_ass_2 odometry_launch.xml" }
ass_2_2 = { cmd = "ros2 launch wasp_as_ass_2 collision_detection_launch.xml" }
ass_2_3 = { cmd = "ros2 launch wasp_as_ass_2 kitti_segmentation_launch.xml" }
ass_2_4 = { cmd = "ros2 launch wasp_as_ass_2 camera_segmentation_launch.xml" }

# Assignment 3 tasks

ass_3 = { cmd = "ros2 launch wasp_as_ass_3 planning_launch.xml" }
ass_3_planner = { cmd = "ros2 run wasp_as_ass_3 path_planner" }
ass_3_gui = { cmd = "ros2 launch wasp_as_ass_3 gui_launch.xml" }

# Assignment 4 tasks

ass_4_manual = { cmd = "ros2 launch wasp_as_ass_4 manual_launch.xml" }
ass_4_hold = { cmd = "ros2 launch wasp_as_ass_4 hold_launch.xml" }
ass_4_pid = { cmd = "ros2 launch wasp_as_ass_4 pid_launch.xml" }