<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>wasp_as_gazebo</name>
  <version>1.0.0</version>
  <description>Gazebo alternative to the Webots simulator for the camera-less assignments (2 collision detection, 4 altitude control)</description>
  <maintainer email="patric@kth.se">Patric Jensfelt</maintainer>
  <license>Apache License 2.0</license>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>turtlebot3_gazebo</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>
  <exec_depend>actuator_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>rqt_plot</exec_depend>
  <exec_depend>rqt_reconfigure</exec_depend>
  <exec_depend>wasp_as</exec_depend>
  <exec_depend>wasp_as_ass_1</exec_depend>
  <exec_depend>wasp_as_ass_2</exec_depend>
  <exec_depend>wasp_as_ass_4</exec_depend>
  <exec_depend>wasp_as_interfaces</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
